---
title: "Principal component analysis"
---

```{r}
#| echo: false
#| message: false
#| results: hide
source(file = "setup_files/setup.R")
```

```{python}
#| echo: false
#| message: false
import shutup;shutup.please()
exec(open('setup_files/setup.py').read())
```

::: {.callout-tip}
## Learning outcomes

- Understand when PCAs can be useful
- Be able to perform a PCA
- Learn how to plot and interpret a screeplot
- Plot and interpret the loadings for each PCA

:::

## Libraries and functions

::: {.callout-note collapse="true"}
## Click to expand

::: {.panel-tabset group="language"}
## R

### Libraries
### Functions

## Python

### Libraries
### Functions
:::
:::

## Purpose and aim

This is a statistical technique for reducing the dimensionality of a data set. The technique aims to find a new set of variables for describing the data. These new variables are made from a weighted sum of the old variables. The weighting is chosen so that the new variables can be ranked in terms of importance in that the first new variable is chosen to account for as much variation in the data as possible. Then the second new variable is chosen to account for as much of the remaining variation in the data as possible, and so on until there are as many new variables as old variables.


## Data and hypotheses

The example in this section uses the following data set:

`data/finches_hybridisation.csv`

These data come from an analysis of gene flow across two finch species [@grant2020]. They are slightly adapted here for illustrative purposes.

## Exercises

### Title {#sec-exr_title}

:::{.callout-exercise}

{{< level 2 >}}

For this exercise we'll be using the data from `data/file.csv`.

::: {.callout-answer collapse="true"}

::: {.panel-tabset group="language"}
## R

## Python

:::
:::
:::

## Summary

::: {.callout-tip}
#### Key points

- PCA allows you to reduce a large number of variables into fewer principal components
- Each PC is made up of a combination of the original variables and captures as much of the variance within the data as possible
- The loadings tell you how much each original variable contributes to each PC
- A screeplot is a graphical representation of the amount of variance explained by each PC
:::
